#!/usr/bin/env bash
# mcp-wrapper.sh — stdio bridge between Claude Code / IDE and the local gateway.
#
# Uses `mcp-remote` (npm) to bridge stdio ↔ streamable-http. The gateway
# exposes one virtual-server endpoint; point MCP_CLIENT_SERVER_URL at it.
#
# Environment variables:
#   MCP_CLIENT_SERVER_URL  (required) Full gateway URL, e.g.
#                          http://127.0.0.1:4444/servers/<UUID>/mcp
#   MCP_GATEWAY_TOKEN      (optional) Bearer token if the gateway requires auth
#   MCP_WRAPPER_NPX        (optional) Override the npx binary path
#
# Generated by forge-kit setup-claude. Safe to run manually.

set -euo pipefail

NPX="${MCP_WRAPPER_NPX:-npx}"
PACKAGE="mcp-remote"

if [[ -z "${MCP_CLIENT_SERVER_URL:-}" ]]; then
  echo '{"jsonrpc":"2.0","error":{"code":-32603,"message":"MCP_CLIENT_SERVER_URL is not set"},"id":null}' >&2
  exit 1
fi

ARGS=("-y" "${PACKAGE}" "${MCP_CLIENT_SERVER_URL}")

if [[ -n "${MCP_GATEWAY_TOKEN:-}" ]]; then
  ARGS+=("--header" "Authorization: Bearer ${MCP_GATEWAY_TOKEN}")
fi

exec "${NPX}" "${ARGS[@]}"
